name: Compile Firmware

on:
  workflow_dispatch:
    inputs:
      git-ref:
        required: false
        type: string
        default: "main"
        description: "Git ref to checkout. Default is main."
      keymap:
        type: string
        required: false
        default: "hmasdevmap"
        description: "Keymap name. Default is hmasdevmap."
      keyboard:
        required: false
        type: string
        default: "hmproto34s"
        description: "Keyboard name. Default is hmproto34s."
      keyboard-tag:
        required: false
        type: string
        default: "main"
        description: "Keyboard branch or tag, like . Default is main."
  workflow_call:
    inputs:
      git-ref:
        required: false
        type: string
        default: "main"
        description: "Git ref to checkout. Default is main."
      keymap:
        type: string
        required: false
        default: "hmasdevmap"
        description: "Keymap name. Default is hmasdevmap."
      keyboard:
        required: false
        type: string
        default: "hmproto34s"
        description: "Keyboard name. Default is hmproto34s."
      keyboard-tag:
        required: false
        type: string
        default: "main"
        description: "Keyboard branch or tag, like . Default is main."

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Setup keyboard firmware repository
        uses: actions/checkout@v4
        with:
          repository: hmasdev/${{ inputs.keyboard }}
          ref: ${{ inputs.keyboard-tag }}
          path: ${{ inputs.keyboard }}_firmware
      - name: Setup this repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git-ref }}
          path: ${{ inputs.keyboard }}_keymap
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install QMK
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user qmk
      - name: Setup QMK
        run: |
          qmk setup -H ~/qmk_firmware -y
      - name: Setup Vial QMK
        run: |
          git clone https://github.com/vial-kb/vial-qmk.git ~/vial-qmk
          cd ~/vial-qmk
          python -m pip install -r requirements.txt
          make git-submodule
          qmk doctor || echo 'qmk doctor failed'
      - name: Copy my keyboards into qmk_firmware
        run: |
          mkdir -p ~/vial-qmk/keyboards/${KEYBOARD_NAME}
          cp -r ./${KEYBOARD_NAME}_firmware/* ~/vial-qmk/keyboards/${KEYBOARD_NAME}/ || echo 'failed to copy'
          cp -r ./${KEYBOARD_NAME}_keymap/* ~/vial-qmk/keyboards/${KEYBOARD_NAME}/ || echo 'failed to copy'
        env:
          KEYBOARD_NAME: "${{ inputs.keyboard }}"
      - name: Compile
        run: |
          cd ~/vial-qmk
          make ${KEYBOARD_NAME}:${KEYMAP_NAME}
        env:
          KEYBOARD_NAME: "${{ inputs.keyboard }}"
          KEYMAP_NAME: ${{ inputs.keymap }}
      - name: Create Artifacts Directory
        run: |
          mkdir -p ~/artifacts
          cp ~/vial-qmk/${KEYBOARD_NAME}_${KEYMAP_NAME}.hex ~/artifacts/
          cp ./${KEYBOARD_NAME}_keymap/LICENSE ~/artifacts/
        env:
          KEYBOARD_NAME: "${{ inputs.keyboard }}"
          KEYMAP_NAME: ${{ inputs.keymap }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.keyboard }}-${{ inputs.keymap }}
          path: ~/artifacts
    permissions:
      contents: read
